name: Lint

on: push

jobs:
   eslint:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4
         - name: Install PNPM
           run: corepack enable && corepack prepare pnpm@10.4.0 --activate
         - name: Install workspaces
           run: pnpm install
         - name: Run linter
           run: pnpm lint
